apiVersion: v1
kind: Service
metadata:
  name: libretranslate-svc
  namespace: libretranslate
spec:
  type: LoadBalancer
  selector:
    app: libretranslate
  ports:
  - port: 80
    targetPort: 5000
