apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate
  namespace: libretranslate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libretranslate
  template:
    metadata:
      labels:
        app: libretranslate
    spec:
      containers:
        - name: libretranslate
          image: 081827876616.dkr.ecr.us-west-2.amazonaws.com/libretranslate
          resources:
            limits:
              memory: "3Gi"
              cpu: "1"
          ports:
            - containerPort: 5000
